export const EVENTS = {
  USER_CONNECTED: "USER_CONNECTED",
  LAYER_LOCKED: "LAYER_LOCKED",
  LOTTIE_UPDATED: "LOTTIE_UPDATED",
  LAYER_UNLOCKED: "LAYER_UNLOCKED",
  BROADCAST_ACTIVE_SESSION: "BROADCAST_ACTIVE_SESSION",
  PROPAGATE_LOTTIE_FILE: "PROPAGATE_LOTTIE_FILE",
} as const;
